[meta]
name     = "QuickChatsDevelopment"
author   = "jtemme8"
category = "Development"
version  = "1.0.0"

[script]
dependencies = [ "NadeoServices" ]

#exports = [ "src/QuickChatter.as" ]
#exports = [ "src/Export.as" ]
#shared_exports = [ "src/ExportShared.as" ]